// Project data types - can be imported client-side safely

export interface KeyAchievement {
  type: 'performance' | 'technical' | 'impact';
  icon: string;
  title: string;
  description: string;
  metrics: string[];
}

export interface ProjectData {
  id: string;
  title: string;
  description: string;
  technologies: string[];
  category: string;
  status: string;
  featured: boolean;
  publishDate: string;
  contentTitle?: string; 
  achievementTitle?: string;
  links: {
    live?: string;
    github?: string;
    demo?: string;
    case_study?: string;
  };
  
  // Auto-discovered content
  images?: {
    hero?: string;
    screenshots?: string[];
    demo?: string;
  };
  content?: {
    overview?: string;
    overviewHtml?: string; // PHASE 3: Rich HTML generated by build script
    challenges?: string[];
    solutions?: string[];
    results?: string[];
    keyAchievements?: KeyAchievement[];
    media?: {
      // New unified format
      items?: Array<{
        type: 'video' | 'image';
        src: string;
        title?: string;
      }>;
      // Legacy format for backward compatibility  
      videos?: string[];
      featured_images?: string[];
    };
  };
}
